### ISSUE TITLE
add support for Mixpanel reserved properties

### ISSUE THREAD

**Issue by ndhoule** [segment-integrations/analytics.js-integration-mixpanel#1]
_From @yields on January 13, 2014 23:1_

https://mixpanel.com/docs/properties-or-segments/special-or-reserved-properties

_Copied from original issue: segmentio/analytics.js-integrations#35_

**Comment by ndhoule** [comment]
_From @DirtyAnalytics on January 13, 2014 23:3_

Some of the properties already get taken care of, we're just missing a few.
$last_login and $ignore are requested by the customer who asked for this.

**Comment by ndhoule** [comment]
_From @ianstormtaylor on January 13, 2014 23:12_

https://mixpanel.com/docs/people-analytics/people-http-specification-insert-data

cc @calvinfo i believe we support the `$ignore_time` through another property but cant remember. calv can you point amir in the right direction? 

@DirtyAnalytics i dont see a straight up `$ignore` did you mean ignore time?

for `$last_login` i'd want to normalize that across services. we usually refer to it as `lastSeen` unless `login` is actually the act of logging in, but that doesnt seem as useful. dunno if mixpanel distinguishes.

**Comment by ndhoule** [comment]
_From @calvinfo on January 13, 2014 23:16_

yeah, [`.active()`](https://github.com/segmentio/facade/blob/master/lib/facade.js#L161-L171) is what you want

**Comment by ndhoule** [comment]
_From @DirtyAnalytics on January 13, 2014 23:24_

I might have messed up. Let me check with the user who asked about this.

**Comment by ndhoule** [comment]
_From @robvolk on January 14, 2014 23:2_

Hey guys, I'm the customer.  Thanks for jumping on this so quickly.  Once it's in place, we can migrate our Mixpanel scripts to Segment.io.

It looks like Mixpanel's docs aren't complete:
```$ignore``` is described here: https://mixpanel.com/help/questions/articles/can-i-exclude-myself-from-mixpanel-data

I'm not sure where I found $last_login, but it looks like you guys may support it already with ```lastSeen```:
http://www.tuicool.com/articles/ZBFv6j

**Comment by ndhoule** [comment]
_From @DirtyAnalytics on February 10, 2014 15:14_

Just had a request to add $signup which is an event name, but Mixpanel does use it for some things in their UI. We would want to change "Signed up" and "Signup" to  $signup when we send that event to Mixpanel.

**Comment by ndhoule** [comment]
_From @ianstormtaylor on February 10, 2014 19:39_

mm yeah that makes sense. luckily the way amir implemented it with regexps it should be a pretty easy check. we might want to start doing `/view(ed)? product/` for them all @yields

**Comment by ndhoule** [comment]
_From @seth-admittedly on February 14, 2014 14:57_

Supporting mixpanel's `$ignore` would be a big help to us, as it's the easiest way of excluding our team from our stats.

**Comment by hankim813** [comment]
this sounds more of a platform spec question. One could argue that segment should spec something out for completing omitting sending data for certain users based on an optional flag, similar to how we treat `.active()`.

`active` is to denote whether that `.identify()` call should be passive (just update traits but not last_seen). We don't have a spec for something like `$ignore`. 

The [mixpanel docs](https://mixpanel.com/help/questions/articles/can-i-exclude-myself-from-mixpanel-data) linked says ideally you want to add custom logic to catch internal employees and add the `$ignore` flag but why not just not call `.identify()` at all? Assuming you wouldn't want your internal employee data going to any tool. 

Will close this issue for inactivity as well but definitely something we should discuss internally regarding if we want to spec something like this.
