### ISSUE TITLE
No version for package.json

### ISSUE THREAD

**Issue by rcline** [segment-integrations/analytics.js-integration-mixpanel#19]
Hey!

There is no version in the package.json file, so when trying to install this integration directly it errors out.  Seems this is the same for most the integrations.  Thanks!!!

**Comment by hankim813** [comment]
@rcline not sure if this is still relevant but if it is, could you expound on this part:

> There is no version in the package.json file, so when trying to install this integration directly it errors out. 

What do you mean installing "directly"? And what is the error you are seeing?

**Comment by f2prateek** [comment]
@hankim813 I believe this is for people using the open source a.js and using a package manager instead of the hosted version.

**Comment by hankim813** [comment]
That's what I assumed but wanted to check.. @rcline feel free to chime in here if this is not the reason for opening this issue. With that said, we're not using NPM to grab the version of Mixpanel's library. We're just using their [latest](https://github.com/segment-integrations/analytics.js-integration-mixpanel/blob/master/lib/index.js#L37). so I don't see us adding support for this. 

@rcline if you are hosting your own, you can manually edit the `package.json`.

**Comment by rcline** [comment]
Thanks @hankim813, indeed we where trying to install with npm.  We have forked the [analytics.js](https://github.com/segmentio/analytics.js) repo to work around this.  Thanks!
