### ISSUE TITLE
add support for e-commerce events

### ISSUE THREAD

**Issue by ndhoule** [segment-integrations/analytics.js-integration-mixpanel#3]
_From @ivolo on June 25, 2014 19:6_

`Completed Order` products array currently arrives as nested `[Object][Object]`

_Copied from original issue: segmentio/analytics.js-integrations#243_

**Comment by ndhoule** [comment]
_From @ianstormtaylor on June 25, 2014 23:27_

What are you thinking we should do instead? I feel like this is not something we can fix easily from our end.

**Comment by hankim813** [comment]
closed for inactivity. please reopen if still issue. Assuming this hasn't come up in awhile, mixpanel may be able to ingest nested objects on their end now
